### ISSUE TITLE
Shulkers attack with mod enabled.

### ISSUE THREAD

**Issue by barrnj001** [JosiahFu/Neutron#1]
I've noticed so far that shulker's will rapid fire attack regardless of whether the mod is enabled or not.

**Comment by ThePotatoArchivist** [comment]
That works as intended. Structure-exclusive mobs stay hostile since you willingly choose to loot a structure.

> ## Exceptions
> 
> Boss mobs and certain structure-exclusive mobs are not turned neutral. This is to retain the challenge of bosses and structures.
> ### List of non-neutral mobs
>
> - Wither
> - Ender Dragon
> - Illagers (besides pillagers)
> - Ravager
> - Vex
> - Piglin Brute
> - Wither Skeleton
> - Guardian
> - Elder Guardian
> - Warden
> - Shulker

**Comment by ThePotatoArchivist** [comment]
Maybe this will be configurable later
